[package]
name = "primitives"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[features]
default = []

[dependencies]
serde = { workspace = true }
strum = { workspace = true }
typeshare = { version = "1.0.4" }
uniffi = { workspace = true }