[bindings.kotlin]
cdylib_name = "juvycore"

[bindings.swift]
ffi_module_name = "JuvyCoreFFI"
generate_module_map = false
experimental_sendable_value_types = true
omit_localized_error_conformance = true